name: New release

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: Release type
        default: Next
        required: true
        options:
        - next
        - patch
        - cut release candidate
        - cut final release
      base-ref:
        description: Base version
        default: master
        required: false

jobs:
  new-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install Dependencies
      run: yarn --frozen-lockfile

    - name: Build
      run: yarn build

    # - name: Trigger next release
    #   id: changesets
    #   uses: ./
    #   with:
    #     nextRelease: true
    #     nextReleaseType: ${{ github.event.inputs.release-type }}
    #     nextReleaseBase: ${{ github.event.inputs.base-ref }}
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - uses: peterjgrainger/action-create-branch@v2.2.0
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     branch: 'release-1.5.0-manual'
    #     sha: '8a2051020292719a1452eff253bedb97d3fc1061'

    - run: npm i -g @rocket.chat/houston@next

    - run: houston create-branch -t ${{ github.event.inputs.release-type }} -b ${{ github.event.inputs.base-ref }}

    - run: |
        git status

        git branch

        git push --set-upstream origin release-1.4.5
