name: New release

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Release type
        default: Next
        required: true
        options:
        - Next
        - Patch
      base-ref:
        description: Base version
        default: master
        required: false

jobs:
  new-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.base-ref }}

    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install Dependencies
      run: yarn --frozen-lockfile

    - name: Build
      run: yarn build

    - name: Try out next release
      id: changesets
      uses: ./
      with:
        nextRelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
